agents:
  queue: "default"

# Nodes with values to reuse in the pipeline.
common_params:
  - &docker_plugin "docker#v5.7.0"
  - &docker_ruby_32_image "public.ecr.aws/docker/library/ruby:3.2.2"
  - &docker_ruby_34_image "public.ecr.aws/docker/library/ruby:3.4.9"

steps:
  #################
  # Build and Test
  #################
  - group: "🧪 Build and Test"
    key: test
    steps:
      - label: "🧪 Ruby 3.2"
        command: |
          echo "--- :rubygems: Setting up Gems"
          bundle install

          echo "--- :rspec: Run Rspec"
          bundle exec rspec --profile 10 --format progress
        plugins:
          - *docker_plugin :
              image: *docker_ruby_32_image

      - label: "🧪 Ruby 3.4"
        command: |
          echo "--- :rubygems: Setting up Gems"
          bundle install

          echo "--- :rspec: Run Rspec"
          bundle exec rspec --profile 10 --format progress
        plugins:
          - *docker_plugin :
              image: *docker_ruby_34_image

  #################
  # Lint
  #################
  - label: ":rubocop: Lint"
    key: rubocop
    command: rubocop
    agents:
      queue: linter

  - label: ":rubygems: Build gem"
    key: gem-build
    command: |
      bundle install
      bundle exec gem build i18n-context-generator.gemspec
    plugins:
      - *docker_plugin :
          image: *docker_ruby_34_image

  #################
  # Push to RubyGems
  #################
  - label: ":rubygems: Publish to RubyGems"
    key: "gem-push"
    if: build.tag != null
    depends_on:
     - test
     - rubocop
     - gem-build
    command: .buildkite/gem-push.sh
    plugins:
      - *docker_plugin :
          image: *docker_ruby_32_image
          propagate-environment: true
          environment:
            - "RUBYGEMS_API_KEY"
